namespaced-key: "glaive"
rename-text: "Глефа"
material: 
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
custom-model-data: 5
show-in-rename-menu: true