namespaced-key: "example"
block-settings:
  dig-speed: 1.0
  drop:
    experience: 0
    drops-default-item: true
  tool:
    type: HAND/SWORD/PICKAXE/AXE/SHOVEL/HOE/SHEARS
    force: false
item:
  name: "Item name"
  custom-model-data: 0
craft:
  show-in-crafts-menu: true
  group: "group"
  shaped-recipe:
    - " P "
    - " P "
    - " P "
  material-list:
    P: PAPER
  item-amount: 1
placing:
  placing-type: BY_BLOCK_FACE/BY_EYE_POSITION
  normal:
    instrument: BANJO
    note: 0
    is-powered: false
  directional:
    block-faces:
      up:
        instrument: BANJO
        note: 0
        is-powered: false
      down:
        instrument: BANJO
        note: 0
        is-powered: true
      east:
        instrument: BANJO
        note: 1
        is-powered: false
      north:
        instrument: BANJO
        note: 1
        is-powered: true
      west:
        instrument: BANJO
        note: 2
        is-powered: false
      south:
        instrument: BANJO
        note: 2
        is-powered: true
  orientable:
    axes:
      x:
        instrument: BANJO
        note: 0
        is-powered: false
      y:
        instrument: BANJO
        note: 0
        is-powered: true
      z:
        instrument: BANJO
        note: 1
        is-powered: false
  placeable-materials:
    - GRASS
    - FERN
sounds:
  place:
    sound-name: "block.wood.place"
    sound-category: BLOCKS
    pitch: 1.0
    volume: 1.0
  break:
    sound-name: "block.wood.break"
    sound-category: BLOCKS
    pitch: 1.0
    volume: 1.0
  step:
    sound-name: "block.wood.step"
    sound-category: PLAYERS
    pitch: 1.0
    volume: 1.0
  hit:
    sound-name: "block.wood.hit"
    sound-category: BLOCKS
    pitch: 1.0
    volume: 1.0