namespaced-key: "over_brand"
rename-text: "Кровавый полэкс"
material: 
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE
custom-model-data: 5
show-in-rename-menu: true